#Sign In Details
userName =
password = 123456

# SignUp Details
enterUserName = t


enterPassword = 123456
confirmPassWord = 123456

invalidEmail = qwerty@gmail.com
passwordInvalid= 12abcdef

enterPasswordL = 12345
confirmPassWordL = 12345

confirmPassWordDiff = 123456789



#Add Account Details
addAccountUserName =
addAccountPassword = 123456

BASE_URL=http://automationpractice.com

defaultBrowser=chrome 
defaultExecutionEnvironment=Local
MACOSBUILD=Sierra

#android Details
Password=
appium_ip_address=0.0.0.0
appium_port=4723

platformName=iOS
automationName=XCUITest
newCommandTimeout=300
Version=7.1.1
#ID=LC56RB455283
DeviceName=emulator-5554
explicit_timeout=45


l
extentConfigPath=/src/main/resources/Config/extent-config.xml
extentReportPath=/ExecutionReports/HTMLReports/extentReport.html

#paths of files to get test data
DataSheetPath=DataSheet/DataSheet.xls
CvsDataSheetPath=DataSheet/
XmlDataSheetPath=DataSheet/DataSheet.xml
DataMode=xls
ReferenceNumberNote=DataSheet/ReferenceNote.txt

columnToLookTestCaseID=0
AutomationControlExcelPath=/src/test/resources/ExcelFiles/AutomationControlSheet.xlsx
logInfoFilePath=ExecutionReports/Logs/appLog.txt
testResultExcelPath=/ExecutionReports/ExcelReport/TestResult.xls
testDataSheet=TestData
testDataExcelPath=src/test/resources/testData/TestData.xlsx

AutomationControlSheet=AppControl
#
HtmlReportFullPath=target/cucumber-html-report.html
screenshotPath=ExecutionReports/FailedScreenshots

GeckoDriverPath=src/main/resources/Driver/geckodriver.exe
IEDriverPath=src/main/resources/Driver/IEDriverServer.exe
ChromeDriverPath=src/main/resources/Driver/chromedriver.exe

# Number to times you want to retry a failed Test Case.
retryCount=0
#wait for given time in Secs before retry to execute Test Case.
retryDelayTime=1


sendMail=Y
HTMLReport=Y
ExcelReport=Y
Logs=N